#!/usr/bin/env python
import RPi.GPIO as GPIO
import car_ctl as c
import socket as s
import time as time
import ConfigParser as cfg
import PCA9685 as servo

# read data from the config file
config = cfg.RawConfigParser()
config.read('config')

# network settings
busnum = config.getint('network', 'busnum') 
HOST = config.get('network', 'HOST')
PORT = config.getint('network','PORT')
BUFSIZ = config.getint('network','BUFSIZ')
CONNECTIONS = config.getint('network','CONNECTIONS')

ADDR = (HOST, PORT) # composit address for socket()


car = c.Car(config)

car.command_car(0,0,0,0,0)

